### ISSUE TITLE
Wiki folder editing is broken

### ISSUE THREAD

**Issue by Vhou-Atroph** [TiddlyWiki/TiddlyDesktop#285]
I've been using TiddlyWiki for a couple years, and finally decided to try out wiki folders. I use TiddlyDesktop as a way to edit my wikis, and have found a couple issues in regards to how it works with wiki folders specifically.

Editing a tiddler and then exiting out of it through any means (closing draft, deleting tiddler, saving edits) creates a completely blank object in the story river.

The steps to reproduce this are:

1. Open wiki folder
2. Create a new tiddler
3. Close draft
4. A blank object should remain in the story river.

![bug](https://github.com/TiddlyWiki/TiddlyDesktop/assets/79807240/c1b01cbf-1b59-4d58-a1ca-4c0dfd7e1281)

This happens every time an individual edits a tiddler regardless of whether it already exists or not, and this can happen multiple times within one session. The only way to remove the objects is to close and re-open the wiki.

**Comment by Jermolene** [comment]
Thank you @Vhou-Atroph I can confirm that I'm seeing the same problem. Looking at the developer console there are a number of JS errors. I'm investigating.

**Comment by rmunn** [comment]
https://github.com/Jermolene/TiddlyWiki5/pull/8007 may fix this once it's been merged into TiddlyWiki. To test that fix before that PR is merged, do the following:

- Close any wikis you may have open in TiddlyDesktop, and exit TiddlyDesktop
- Find your TiddlyDesktop install location
- Open the `tiddlywiki` folder inside TiddlyDesktop
- Open the `boot` folder and edit `boot.js` with a text editor: VS Code if you have it, but Notepad will work in a pinch
- Search for the text `sjcl`. You should find `var sjcl = ...` inside a `$tw.utils.Crypto` function
- Add a line saying `$tw.sjcl = sjcl`, right above the `this.setPassword = ...` line
- Save the file and exit the text editor
- Now go back to the tiddlywiki folder, and open up `core`, then `modules`, then `filters`
- Edit the `crypto.js` file
- In the line that starts with `return sjcl.codec.hex ...`, there are two occurrences of `sjcl`. Replace both of them with `$tw.sjcl`, leaving the rest of the line unchanged.
- Save the file and exit the text editor
- Restart TiddlyDeskop and reopen your wiki folder(s)
- Try adding a new tillder, and it should work as expected now

**Comment by Vhou-Atroph** [comment]
@rmunn 
Can confirm this fixes the issue- thank you!

**Comment by Jermolene** [comment]
Thanks @rmunn I'll build a new prerelease of TiddlyDesktop as soon as I get the chance. (We could do with CI on TiddlyDesktop).

**Comment by rmunn** [comment]
I believe this is fixed in the [v0.0.20 release](https://github.com/TiddlyWiki/TiddlyDesktop/releases/tag/v0.0.20). @Vhou-Atroph can you confirm that v0.0.20 fixes this, then close the issue?

**Comment by Vhou-Atroph** [comment]
@rmunn, the issue persists on my new download of v0.0.20. 

Opening the `boot.js` file, I do not see the changes made in [your original fix](https://github.com/TiddlyWiki/TiddlyDesktop/issues/285#issuecomment-1963182247). `crypto.js` similarly does not have the same fixes.

After a little investigation, it seems the `boot.js` bundled with the latest version of TiddlyDesktop looks identical to the [version from the release of TiddlyWiki 5.3.0](https://github.com/Jermolene/TiddlyWiki5/blob/v5.3.0/boot/boot.js). For reference, [here's an online comparison between the two files](https://www.diffchecker.com/37NAG9ei/). The copy of `boot.js` from TiddlyWiki 5.3.0 is shown on the left, and the copy bundled with TiddlyDesktop 0.0.20 is shown on the right.

**Comment by rmunn** [comment]
Looks like the `package-lock.json` file is keeping the tiddlywiki version at commit 5c5543815b66c95938862a4db71cf6ea36cfe143, and `npm install` isn't updating the verison of a Git repo dependency the way I'd have expected it to.

@Jermolene, next time you prepare a TiddlyDesktop release, you might need to put a commit hash into the `package.json` file explicitly, e.g. 984863065ecc6ca7cd6609fd27da7845abc386f7 to get the commit where my bugfix was merged in, or 070327cb5708cfad104e2f325115203b499af631 to get the current most recent TiddlyWiki5 commit.

**Comment by rmunn** [comment]
@Vhou-Atroph - Could you test a TiddlyDesktop prerelease to see if it fixes the bug? At https://github.com/TiddlyWiki/TiddlyDesktop/actions/runs/8185198661?pr=296 you should see a bunch of release candidates for v0.0.21. (Due to a quirk of the GitHub Actions build process that I can't work around, they will be .zip.zip files, i.e. a .zip file that contains a .zip file that contains the actual release candidate. Don't worry, the eventual release will not be double-zipped). Could you download the one that works for your system (win64, linux64, whatever) and test that it finally does fix this bug? Thanks!

**Comment by Vhou-Atroph** [comment]
@rmunn I can confirm that the bug has been fixed in the actions build you have linked.

I'll preemptively close the issue here ahead of a full release. Thank you once again!
